### ISSUE TITLE
Pop Authorization header before redirecting

### ISSUE THREAD

**Issue by amercader** [TkTech/ckanext-cloudstorage#13]
See ckan/datapusher#116 for previous discussion.

Basically what is happening is that the DataPusher is sending a request to download the file that includes the CKAN `Authorization` header (so we can handle authorization at the CKAN level). But then this same header is forwarded to AWS, which doesn't like it:

```
<?xml version="1.0" encoding="UTF-8"?> 
<Error>
    <Code>InvalidArgument</Code>
     <Message>Authorization header is invalid -- one and only one ' ' (space) required</Message>
     <ArgumentName>Authorization</Argum...
```

I think that the `Authorization` header should be stripped before doing the redirect [here](https://github.com/TkTech/ckanext-cloudstorage/blob/master/ckanext/cloudstorage/controller.py#L53) but I'm not familiar with the inner workings of the extension @TkTech.

This might be also the cause of #7.

**Comment by TkTech** [comment]
Any ideas for doing CI tests for these things without having an active AWS account?

**Comment by rhunwicks** [comment]
@TkTech I don't think this can be fixed in CloudStorage because you are only returning the Redirect to the new location. It is Datapusher that is adding the Authorization header and then leaving it in when it follows the redirect.

See my comment at https://github.com/ckan/datapusher/issues/116#issuecomment-336464225

**Comment by rhunwicks** [comment]
Also, the trunk version of datapusher no longer has the problem.
